/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frame;

import Controlador.UsuariosControlador;
import Main.Datos;
import Modelos.Usuarios;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import java.sql.DriverManager;
import java.sql.SQLException;

/**
 *
 * @author fede_
 */
public class Registro extends javax.swing.JFrame {

    /**
     * Creates new form Registro
     */
    public Registro() {
        initComponents();
        this.setLocationRelativeTo(null);//SIRVE PARA QUE APARESCA EN EL CENTRO LA VENTANA
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblNombre = new javax.swing.JLabel();
        lblApellido = new javax.swing.JLabel();
        lblNombreDeUsuario = new javax.swing.JLabel();
        lblContraseña = new javax.swing.JLabel();
        btnRegistro = new javax.swing.JButton();
        txtApellido = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jCheckBox1 = new javax.swing.JCheckBox();
        btnVolverRegistro = new javax.swing.JButton();
        txtNombre = new javax.swing.JTextField();
        txtNombreDeUsuario = new javax.swing.JTextField();
        txtContraseña = new javax.swing.JPasswordField();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 102, 0));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 51, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNombre.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblNombre.setForeground(new java.awt.Color(204, 204, 204));
        lblNombre.setText("NOMBRE");
        jPanel1.add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, -1, 20));

        lblApellido.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblApellido.setForeground(new java.awt.Color(204, 204, 204));
        lblApellido.setText("APELLIDO");
        jPanel1.add(lblApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, -1, 20));

        lblNombreDeUsuario.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblNombreDeUsuario.setForeground(new java.awt.Color(204, 204, 204));
        lblNombreDeUsuario.setText("NOMBRE DE USUARIO");
        jPanel1.add(lblNombreDeUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, -1, -1));

        lblContraseña.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblContraseña.setForeground(new java.awt.Color(204, 204, 204));
        lblContraseña.setText("CONTRASEÑA");
        jPanel1.add(lblContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, -1, 20));

        btnRegistro.setBackground(new java.awt.Color(0, 153, 204));
        btnRegistro.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        btnRegistro.setText("REGISTRAR");
        btnRegistro.setBorder(null);
        btnRegistro.setBorderPainted(false);
        btnRegistro.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnRegistro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegistroMouseClicked(evt);
            }
        });
        btnRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistroActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 330, 110, 40));

        txtApellido.setBackground(new java.awt.Color(0, 51, 102));
        txtApellido.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        txtApellido.setForeground(new java.awt.Color(204, 204, 204));
        txtApellido.setText("Ingrese un apellido");
        txtApellido.setBorder(null);
        txtApellido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtApellidoMouseClicked(evt);
            }
        });
        txtApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidoActionPerformed(evt);
            }
        });
        jPanel1.add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 230, 20));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 230, 10));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 230, 10));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 230, 10));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, 230, 10));

        jCheckBox1.setBackground(new java.awt.Color(0, 51, 102));
        jCheckBox1.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jCheckBox1.setForeground(new java.awt.Color(204, 204, 204));
        jCheckBox1.setText("Acepta los terminos y condiciones de uso");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, 250, -1));

        btnVolverRegistro.setBackground(new java.awt.Color(0, 153, 204));
        btnVolverRegistro.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        btnVolverRegistro.setText("VOLVER");
        btnVolverRegistro.setBorder(null);
        btnVolverRegistro.setBorderPainted(false);
        btnVolverRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverRegistroActionPerformed(evt);
            }
        });
        jPanel1.add(btnVolverRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, 110, 40));

        txtNombre.setBackground(new java.awt.Color(0, 51, 102));
        txtNombre.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        txtNombre.setForeground(new java.awt.Color(204, 204, 204));
        txtNombre.setText("ingrese un nombre");
        txtNombre.setBorder(null);
        txtNombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtNombreMouseClicked(evt);
            }
        });
        jPanel1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 230, 20));

        txtNombreDeUsuario.setBackground(new java.awt.Color(0, 51, 102));
        txtNombreDeUsuario.setForeground(new java.awt.Color(204, 204, 204));
        txtNombreDeUsuario.setText("ingrese un nombre de usuario");
        txtNombreDeUsuario.setBorder(null);
        txtNombreDeUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtNombreDeUsuarioMouseClicked(evt);
            }
        });
        jPanel1.add(txtNombreDeUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 184, 230, 20));

        txtContraseña.setBackground(new java.awt.Color(0, 51, 102));
        txtContraseña.setForeground(new java.awt.Color(204, 204, 204));
        txtContraseña.setText("ingrese una contraseña");
        txtContraseña.setBorder(null);
        txtContraseña.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtContraseñaMouseClicked(evt);
            }
        });
        jPanel1.add(txtContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 244, 230, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 340, 390));

        jPanel2.setBackground(new java.awt.Color(102, 204, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 255, 255));
        jLabel2.setText("REGISTRO");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, -1, -1));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 150)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ic_person_add_128_28581.png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 130, 100));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 390));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistroActionPerformed
        

        String nombre = txtNombre.getText().trim();
        String hash = txtContraseña.getText().trim();
        String usuarios = txtNombreDeUsuario.getText().trim();
        String apellido = txtApellido.getText().trim();
        
        Usuarios usuario = new Usuarios(nombre, hash, usuarios, apellido);
        
        try {
            int addUsuarios = UsuariosControlador.addUsuarios(usuario);
            if (addUsuarios > 0) {
                JOptionPane.showMessageDialog(rootPane, "Registro exitoso!");
            }
        } catch (ClassNotFoundException | SQLException e){
            e.printStackTrace();
        } finally {
        IniciarSesion V = new IniciarSesion();
        V.setVisible(true);
        this.setVisible(false);
            }
        
        txtNombre.setText("");
        txtContraseña.setText("");
        txtNombreDeUsuario.setText("");
        txtApellido.setText("");
        
        /* IniciarSesion a = new IniciarSesion();   //COMENTADO POR QUE SOLO DEBERIA REGISTRAR NO VOLVER AL INICIO
        a.setVisible(true);
        this.setVisible(false);*/
    }//GEN-LAST:event_btnRegistroActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void txtApellidoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtApellidoMouseClicked
        // TODO add your handling code here:
        txtApellido.setText(""); //SIRVE PARA PODER ESCRIBIR SINO NO TE DEJA LA BARRA
    }//GEN-LAST:event_txtApellidoMouseClicked

    private void btnVolverRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverRegistroActionPerformed
        // TODO add your handling code here:
        IniciarSesion V = new IniciarSesion();
        V.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnVolverRegistroActionPerformed

    private void txtNombreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNombreMouseClicked
        // TODO add your handling code here:
        txtNombre.setText(""); //SIRVE PARA PODER ESCRIBIR SINO NO TE DEJA LA BARRA
    }//GEN-LAST:event_txtNombreMouseClicked

    private void txtNombreDeUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNombreDeUsuarioMouseClicked
        // TODO add your handling code here:
        txtNombreDeUsuario.setText(""); //SIRVE PARA PODER ESCRIBIR SINO NO TE DEJA LA BARRA
    }//GEN-LAST:event_txtNombreDeUsuarioMouseClicked

    private void txtContraseñaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtContraseñaMouseClicked
        // TODO add your handling code here:
        txtContraseña.setText(""); //SIRVE PARA PODER ESCRIBIR SINO NO TE DEJA LA BARRA
    }//GEN-LAST:event_txtContraseñaMouseClicked

    private void txtApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidoActionPerformed

    private void btnRegistroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistroMouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this,"Usted se aregistrado correctamente", "Registro" ,JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnRegistroMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistro;
    private javax.swing.JButton btnVolverRegistro;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel lblApellido;
    private javax.swing.JLabel lblContraseña;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblNombreDeUsuario;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JPasswordField txtContraseña;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNombreDeUsuario;
    // End of variables declaration//GEN-END:variables
}
